# Generated by Django 4.2.5 on 2023-10-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='careg',
            new_name='categ',
        ),
    ]
